DROP DATABASE Auction;

CREATE DATABASE Auction
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE Auction;

CREATE TABLE Users
(
    userID VARCHAR(255) PRIMARY KEY,
    pwhash VARCHAR(255) NOT NULL,
    fName VARCHAR(20) NOT NULL,
    lName VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL,
    userType VARCHAR(10) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    updatedAt TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
)
engine = INNODB;

CREATE TABLE Items
(
    itemID VARCHAR(255) PRIMARY KEY,
    title VARCHAR(40) NOT NULL,
    description text NOT NULL,
    category VARCHAR(20) NOT NULL,
    startingPrice DECIMAL(7,2) NOT NULL,
    reservePrice DECIMAL (7,2) NOT NULL,
    startDateTime datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
    endDateTime datetime NOT NULL,
    image_location varchar(255),
    userID VARCHAR(255) NOT NULL,
    bidID VARCHAR(255) NOT NULL, 
    FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE
)
engine = INNODB;

CREATE TABLE Bids
(
    bidID VARCHAR(255) PRIMARY KEY,
    createdAt datetime DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    amount DECIMAL (7,2) NOT NULL,
    userID VARCHAR(255) NOT NULL,
    itemID VARCHAR(255) NOT NULL,
    FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (itemID) REFERENCES Items(itemID) ON UPDATE CASCADE ON DELETE CASCADE
)
engine = INNODB;

CREATE TABLE WatchList
(
    userID VARCHAR(255) NOT NULL,
    itemID VARCHAR(255) NOT NULL,
    FOREIGN KEY (userID) REFERENCES Users(userID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (itemID) REFERENCES Items(itemID) ON UPDATE CASCADE ON DELETE CASCADE
)
engine = INNODB;

ALTER TABLE Auction.Items
ADD FOREIGN KEY (bidID) REFERENCES Bids(bidID)
ON UPDATE CASCADE
ON DELETE CASCADE